name: burn_scan
description: Offline-first burn assessment interface for clinical workflows.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.19.0
  path_provider: ^2.1.2
  pdf: ^3.10.8
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
